# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: map_reduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10map_reduce.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x02(\x02\x12\t\n\x01y\x18\x02 \x02(\x02\"<\n\nMapRequest\x12\x13\n\x0binput_split\x18\x01 \x03(\x05\x12\x19\n\tcentroids\x18\x02 \x03(\x0b\x32\x06.Point\"7\n\tMapOutput\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x02(\x05\x12\x15\n\x05point\x18\x02 \x02(\x0b\x32\x06.Point\"P\n\x0bMapResponse\x12\x11\n\tmapper_id\x18\x01 \x02(\x05\x12\x0e\n\x06status\x18\x02 \x02(\t\x12\x1e\n\nmap_output\x18\x03 \x03(\x0b\x32\n.MapOutput\"-\n\x17IntermediateDataRequest\x12\x12\n\nreducer_id\x18\x01 \x02(\x05\"J\n\x18IntermediateDataResponse\x12\x1e\n\nmap_output\x18\x01 \x03(\x0b\x32\n.MapOutput\x12\x0e\n\x06status\x18\x02 \x02(\t\"\x0f\n\rReduceRequest\":\n\x0cNewCentroids\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x02(\x05\x12\x15\n\x05point\x18\x02 \x02(\x0b\x32\x06.Point\"Z\n\x0eReduceResponse\x12\x12\n\nreducer_id\x18\x01 \x02(\x05\x12\x0e\n\x06status\x18\x02 \x02(\t\x12$\n\rnew_centroids\x18\x03 \x03(\x0b\x32\r.NewCentroids2\x0f\n\rMasterService2\x81\x01\n\rMapperService\x12\"\n\x03Map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12L\n\x13GetIntermediateData\x12\x18.IntermediateDataRequest\x1a\x19.IntermediateDataResponse\"\x00\x32=\n\x0eReducerService\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'map_reduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=20
  _globals['_POINT']._serialized_end=49
  _globals['_MAPREQUEST']._serialized_start=51
  _globals['_MAPREQUEST']._serialized_end=111
  _globals['_MAPOUTPUT']._serialized_start=113
  _globals['_MAPOUTPUT']._serialized_end=168
  _globals['_MAPRESPONSE']._serialized_start=170
  _globals['_MAPRESPONSE']._serialized_end=250
  _globals['_INTERMEDIATEDATAREQUEST']._serialized_start=252
  _globals['_INTERMEDIATEDATAREQUEST']._serialized_end=297
  _globals['_INTERMEDIATEDATARESPONSE']._serialized_start=299
  _globals['_INTERMEDIATEDATARESPONSE']._serialized_end=373
  _globals['_REDUCEREQUEST']._serialized_start=375
  _globals['_REDUCEREQUEST']._serialized_end=390
  _globals['_NEWCENTROIDS']._serialized_start=392
  _globals['_NEWCENTROIDS']._serialized_end=450
  _globals['_REDUCERESPONSE']._serialized_start=452
  _globals['_REDUCERESPONSE']._serialized_end=542
  _globals['_MASTERSERVICE']._serialized_start=544
  _globals['_MASTERSERVICE']._serialized_end=559
  _globals['_MAPPERSERVICE']._serialized_start=562
  _globals['_MAPPERSERVICE']._serialized_end=691
  _globals['_REDUCERSERVICE']._serialized_start=693
  _globals['_REDUCERSERVICE']._serialized_end=754
# @@protoc_insertion_point(module_scope)
