# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import marketCentralPlatform_pb2 as marketCentralPlatform__pb2


class MarketCentralPlatformStub(object):
    """Market Central Platform service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sellerRegisteration = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/sellerRegisteration',
                request_serializer=marketCentralPlatform__pb2.sellerRegisterationRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.sellerRegisterationResp.FromString,
                )
        self.itemSold = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemSold',
                request_serializer=marketCentralPlatform__pb2.itemSoldRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemSoldResp.FromString,
                )
        self.itemUpdated = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemUpdated',
                request_serializer=marketCentralPlatform__pb2.itemUpdatedRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemUpdatedResp.FromString,
                )
        self.itemRemoved = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemRemoved',
                request_serializer=marketCentralPlatform__pb2.itemRemovedRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemRemovedResp.FromString,
                )
        self.itemsDisplayed = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemsDisplayed',
                request_serializer=marketCentralPlatform__pb2.itemsDisplayedRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemsDisplayedResp.FromString,
                )
        self.buyerRegisteration = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/buyerRegisteration',
                request_serializer=marketCentralPlatform__pb2.buyerRegisterationRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.buyerRegisterationResp.FromString,
                )
        self.itemSearch = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemSearch',
                request_serializer=marketCentralPlatform__pb2.itemSearchRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemSearchResp.FromString,
                )
        self.itemBought = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemBought',
                request_serializer=marketCentralPlatform__pb2.itemBoughtRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemBoughtResp.FromString,
                )
        self.itemWishlisted = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemWishlisted',
                request_serializer=marketCentralPlatform__pb2.itemWishlistedRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemWishlistedResp.FromString,
                )
        self.itemRated = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemRated',
                request_serializer=marketCentralPlatform__pb2.itemRatedRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.itemRatedResp.FromString,
                )
        self.clientNotified = channel.unary_unary(
                '/endpoints.marketCentralPlatform.MarketCentralPlatform/clientNotified',
                request_serializer=marketCentralPlatform__pb2.clientNotifiedRqst.SerializeToString,
                response_deserializer=marketCentralPlatform__pb2.clientNotifiedResp.FromString,
                )


class MarketCentralPlatformServicer(object):
    """Market Central Platform service
    """

    def sellerRegisteration(self, request, context):
        """Seller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemSold(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemUpdated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemRemoved(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemsDisplayed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def buyerRegisteration(self, request, context):
        """Buyer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemBought(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemWishlisted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def itemRated(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clientNotified(self, request, context):
        """RPC Notification 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketCentralPlatformServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sellerRegisteration': grpc.unary_unary_rpc_method_handler(
                    servicer.sellerRegisteration,
                    request_deserializer=marketCentralPlatform__pb2.sellerRegisterationRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.sellerRegisterationResp.SerializeToString,
            ),
            'itemSold': grpc.unary_unary_rpc_method_handler(
                    servicer.itemSold,
                    request_deserializer=marketCentralPlatform__pb2.itemSoldRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemSoldResp.SerializeToString,
            ),
            'itemUpdated': grpc.unary_unary_rpc_method_handler(
                    servicer.itemUpdated,
                    request_deserializer=marketCentralPlatform__pb2.itemUpdatedRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemUpdatedResp.SerializeToString,
            ),
            'itemRemoved': grpc.unary_unary_rpc_method_handler(
                    servicer.itemRemoved,
                    request_deserializer=marketCentralPlatform__pb2.itemRemovedRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemRemovedResp.SerializeToString,
            ),
            'itemsDisplayed': grpc.unary_unary_rpc_method_handler(
                    servicer.itemsDisplayed,
                    request_deserializer=marketCentralPlatform__pb2.itemsDisplayedRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemsDisplayedResp.SerializeToString,
            ),
            'buyerRegisteration': grpc.unary_unary_rpc_method_handler(
                    servicer.buyerRegisteration,
                    request_deserializer=marketCentralPlatform__pb2.buyerRegisterationRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.buyerRegisterationResp.SerializeToString,
            ),
            'itemSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.itemSearch,
                    request_deserializer=marketCentralPlatform__pb2.itemSearchRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemSearchResp.SerializeToString,
            ),
            'itemBought': grpc.unary_unary_rpc_method_handler(
                    servicer.itemBought,
                    request_deserializer=marketCentralPlatform__pb2.itemBoughtRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemBoughtResp.SerializeToString,
            ),
            'itemWishlisted': grpc.unary_unary_rpc_method_handler(
                    servicer.itemWishlisted,
                    request_deserializer=marketCentralPlatform__pb2.itemWishlistedRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemWishlistedResp.SerializeToString,
            ),
            'itemRated': grpc.unary_unary_rpc_method_handler(
                    servicer.itemRated,
                    request_deserializer=marketCentralPlatform__pb2.itemRatedRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.itemRatedResp.SerializeToString,
            ),
            'clientNotified': grpc.unary_unary_rpc_method_handler(
                    servicer.clientNotified,
                    request_deserializer=marketCentralPlatform__pb2.clientNotifiedRqst.FromString,
                    response_serializer=marketCentralPlatform__pb2.clientNotifiedResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoints.marketCentralPlatform.MarketCentralPlatform', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketCentralPlatform(object):
    """Market Central Platform service
    """

    @staticmethod
    def sellerRegisteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/sellerRegisteration',
            marketCentralPlatform__pb2.sellerRegisterationRqst.SerializeToString,
            marketCentralPlatform__pb2.sellerRegisterationResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemSold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemSold',
            marketCentralPlatform__pb2.itemSoldRqst.SerializeToString,
            marketCentralPlatform__pb2.itemSoldResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemUpdated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemUpdated',
            marketCentralPlatform__pb2.itemUpdatedRqst.SerializeToString,
            marketCentralPlatform__pb2.itemUpdatedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemRemoved(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemRemoved',
            marketCentralPlatform__pb2.itemRemovedRqst.SerializeToString,
            marketCentralPlatform__pb2.itemRemovedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemsDisplayed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemsDisplayed',
            marketCentralPlatform__pb2.itemsDisplayedRqst.SerializeToString,
            marketCentralPlatform__pb2.itemsDisplayedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def buyerRegisteration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/buyerRegisteration',
            marketCentralPlatform__pb2.buyerRegisterationRqst.SerializeToString,
            marketCentralPlatform__pb2.buyerRegisterationResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemSearch',
            marketCentralPlatform__pb2.itemSearchRqst.SerializeToString,
            marketCentralPlatform__pb2.itemSearchResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemBought(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemBought',
            marketCentralPlatform__pb2.itemBoughtRqst.SerializeToString,
            marketCentralPlatform__pb2.itemBoughtResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemWishlisted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemWishlisted',
            marketCentralPlatform__pb2.itemWishlistedRqst.SerializeToString,
            marketCentralPlatform__pb2.itemWishlistedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def itemRated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/itemRated',
            marketCentralPlatform__pb2.itemRatedRqst.SerializeToString,
            marketCentralPlatform__pb2.itemRatedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def clientNotified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.marketCentralPlatform.MarketCentralPlatform/clientNotified',
            marketCentralPlatform__pb2.clientNotifiedRqst.SerializeToString,
            marketCentralPlatform__pb2.clientNotifiedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
