# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x17\x65ndpoints.notifications\"f\n\x12\x63lientNotifiedRqst\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_address\x18\x02 \x01(\t\x12\x14\n\x0citem_details\x18\x03 \x01(\t\x12\x0f\n\x07verbose\x18\x04 \x01(\t\"6\n\x12\x63lientNotifiedResp\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07verbose\x18\x02 \x01(\t2{\n\rNotifications\x12j\n\x0e\x63lientNotified\x12+.endpoints.notifications.clientNotifiedRqst\x1a+.endpoints.notifications.clientNotifiedRespB9\n!com.google.endpoints.notificationB\x12NotificationsProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n!com.google.endpoints.notificationB\022NotificationsProtoP\001'
  _globals['_CLIENTNOTIFIEDRQST']._serialized_start=47
  _globals['_CLIENTNOTIFIEDRQST']._serialized_end=149
  _globals['_CLIENTNOTIFIEDRESP']._serialized_start=151
  _globals['_CLIENTNOTIFIEDRESP']._serialized_end=205
  _globals['_NOTIFICATIONS']._serialized_start=207
  _globals['_NOTIFICATIONS']._serialized_end=330
# @@protoc_insertion_point(module_scope)
