# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notification_pb2 as notification__pb2


class NotificationsStub(object):
    """Notifications service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.clientNotified = channel.unary_unary(
                '/endpoints.notifications.Notifications/clientNotified',
                request_serializer=notification__pb2.clientNotifiedRqst.SerializeToString,
                response_deserializer=notification__pb2.clientNotifiedResp.FromString,
                )


class NotificationsServicer(object):
    """Notifications service
    """

    def clientNotified(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'clientNotified': grpc.unary_unary_rpc_method_handler(
                    servicer.clientNotified,
                    request_deserializer=notification__pb2.clientNotifiedRqst.FromString,
                    response_serializer=notification__pb2.clientNotifiedResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'endpoints.notifications.Notifications', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Notifications(object):
    """Notifications service
    """

    @staticmethod
    def clientNotified(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/endpoints.notifications.Notifications/clientNotified',
            notification__pb2.clientNotifiedRqst.SerializeToString,
            notification__pb2.clientNotifiedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
