# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"[\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x04\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x04\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x04\"V\n\x0cVoteResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\x04\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x03 \x01(\x08\x12\x13\n\x0bleaderLease\x18\x04 \x01(\x01\"C\n\x0bSuffixEntry\x12\n\n\x02op\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04term\x18\x04 \x01(\x05\"\xa8\x01\n\nLogRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\x04\x12\x13\n\x0b\x63urrentTerm\x18\x02 \x01(\x05\x12\x11\n\tprefixLen\x18\x03 \x01(\x04\x12\x12\n\nprefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0c\x63ommitLength\x18\x05 \x01(\x04\x12!\n\x06suffix\x18\x06 \x03(\x0b\x32\x11.raft.SuffixEntry\x12\x13\n\x0bleaderLease\x18\x07 \x01(\x01\"I\n\x0bLogResponse\x12\x0e\n\x06nodeId\x18\x01 \x01(\x04\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x08\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x32\xc0\x01\n\x0bRaftService\x12\x36\n\rVoteRequested\x12\x11.raft.VoteRequest\x1a\x12.raft.VoteResponse\x12>\n\x0bServeClient\x12\x15.raft.ServeClientArgs\x1a\x16.raft.ServeClientReply\"\x00\x12\x39\n\x10LoggingRequested\x12\x10.raft.LogRequest\x1a\x11.raft.LogResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=20
  _globals['_VOTEREQUEST']._serialized_end=111
  _globals['_VOTERESPONSE']._serialized_start=113
  _globals['_VOTERESPONSE']._serialized_end=199
  _globals['_SUFFIXENTRY']._serialized_start=201
  _globals['_SUFFIXENTRY']._serialized_end=268
  _globals['_LOGREQUEST']._serialized_start=271
  _globals['_LOGREQUEST']._serialized_end=439
  _globals['_LOGRESPONSE']._serialized_start=441
  _globals['_LOGRESPONSE']._serialized_end=514
  _globals['_SERVECLIENTARGS']._serialized_start=516
  _globals['_SERVECLIENTARGS']._serialized_end=550
  _globals['_SERVECLIENTREPLY']._serialized_start=552
  _globals['_SERVECLIENTREPLY']._serialized_end=619
  _globals['_RAFTSERVICE']._serialized_start=622
  _globals['_RAFTSERVICE']._serialized_end=814
# @@protoc_insertion_point(module_scope)
